###

POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "ideia",
    "marcadores": [
        {"local": "quarto"},
        {"personagem": "Lola"},
        {"acao": "curiosa"}
    ],
    "valores": [
        {"latitude": -27.6084177},
        {"longitude": -48.6354691},
        {"altitude": 80}
    ]
}

###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "vga",
    "marcadores": [
        {"fabricante": "nvidia"},
        {"arquitetura": "rtx"}
    ],
    "valores": [
        {"serie": 3000 },
        {"modelo": 3080 }
    ]
}

###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "vga",
    "marcadores": [
        {"url":"https://www.nvidia.com/pt-br/geforce/graphics-cards/30-series/rtx-3080/"},
        {"fabricante": "nvidia"},
        {"arquitetura": "rtx"}
    ],
    "valores": [
        {"serie": 3000 },
        {"modelo": 3080 }
    ]
}

###
